#!/bin/bash

export HISTCONTROL=erasedups
export PATH=$PATH:~/bin

VOLTA_HOME="$HOME/.volta"

if [ -d "$VOLTA_HOME" ]; then
    PATH="$VOLTA_HOME/bin:$PATH"
    export VOLTA_HOME PATH
fi

shopt -s histappend
shopt -s cmdhist

source $(dirname $(readlink -f $BASH_SOURCE))/ssh-agent.sh
source $(dirname $(readlink -f $BASH_SOURCE))/gitprompt.sh

# Prompt with git branch
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
CYAN="\[\033[0;36m\]"
GRAY="\[\033[1;37m\]"
BLACK="\[\033[0;30m\]"
OFF="\[\033[0m\]"

GIT_PS1_SHOWDIRTYSTATE=true

PS1="[$CYAN\u@\h $GREEN\W$YELLOW\$(__git_ps1 \" (%s)\")$OFF]\$ "
