alias readlink=greadlink

source $(dirname $(readlink -f $BASH_SOURCE))/../common/bashrc

# Add fun emoji unless we're in pycharm.
[ -z "$PYCHARM" ] && PS1="[$CYAN\u@\h $GREEN\W$YELLOW\$(__git_ps1 \" (%s)\")$OFF]🍄  "

if [ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]; then
	source /usr/local/opt/chruby/share/chruby/chruby.sh
	chruby 2.0.0
fi

export EDITOR='subl -w -n'
alias ls='ls -G'
