#!/bin/bash

if [ $(uname) != "Darwin" ]; then
    echo "Unsupported platform: $(uname)" >&2
    exit 1
fi

while read -r line; do
    sname=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $2}')
    sdev=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $4}')
    #echo "Current service: $sname, $sdev, $currentservice"
    if [ -n "$sdev" ]; then
        ifout="$(ifconfig "$sdev" 2>/dev/null)"
        echo "$ifout" | grep 'status: active' > /dev/null 2>&1
        rc="$?"
        if [ "$rc" -eq 0 ]; then
            currentservice="$sname"
            currentdevice="$sdev"
            currentmac=$(echo "$ifout" | awk '/ether/{print $2}')
            currentinet=$(echo "$ifout" | awk '/inet /{print $2}')
            currentinet6=$(echo "$ifout" | awk '/inet6 /{print $2}')

            # may have multiple active devices, so echo it here
            printf "%s\t%-30s\t%s\t%-15s\t%s\n" "$currentdevice" "$currentservice" "$currentmac" "$currentinet" "$currentinet6"
        fi
    fi
done <<< "$(networksetup -listnetworkserviceorder | grep 'Hardware Port')"

if [ -z "$currentservice" ]; then
    >&2 echo "Could not find current service"
    exit 1
fi
